name: muse_icons_workspace

repository:
  type: github
  origin: https://github.com
  owner: MuseTools
  name: muse_icons

packages:
  - "apps/**"
  - "packages/**"

command:
  version:
    workspaceChangelog: false

scripts:
  analyze:
    exec: dart analyze .

