name: muse_icons
description: "Simple icon library using font icons"
version: 1.0.0
homepage: https://github.com/Eugene2799/muse_icons
repository: https://github.com/eugene2799/muse_icons/tree/master/packages/muse_icons

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  fonts:
    - family: MuseIcons
      fonts:
        - asset: fonts/muse_icons.ttf
