name: muse_demo
description: "A Demo project for Muse Icons."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # muse_icons: ^1.0.0 # For remote development
  muse_icons:
    path: ../../packages/muse_icons # For local development

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
